### ISSUE TITLE
Deploy notification

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-webpack#278]
Add an option to configure deploy notification in addition to uploading source maps. Maybe something like this:

```js
const webpackConfig = {
  plugins: [new HoneybadgerSourceMapPlugin({
    apiKey: 'abc123',
    assetsUrl: ASSETS_URL,
    revision: 'master',
    deploy: {
        environment: 'production',
        repository: 'git repo url',
        local_username: 'deploy user'
    }
  })]
}
```

https://docs.honeybadger.io/api/deployments.html

**Comment by ParamagicDev** [comment]
Ill tackle this once the `node-fetch` PR gets merged and gets some real world testing.
