### ISSUE TITLE
Rails/Webpacker recipe

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-webpack#319]
See [recipes](https://www.notion.so/honeybadger/549be6376a6246e19d6291bf8bdcee69?v=02c2f9dfbe41498ebd8f43880fb4e782). I'd like a simple guide/checklist for how to configure `@honeybadger-io/webpack` in a new Rails app w/ Webpacker (including generating the Rails app).

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3p9lt)

**Comment by subzero10** [comment]
How to setup a fresh Rails project (on a Mac) and add `@honeybadger-io/webpack` to send source maps to Honeybadger.

# Create a fresh new project

1. Make sure that you have all the prerequisites installed: `Ruby`, `sqlite3` , `nodejs`, `yarn`, `rails`. If not, you can follow [here](https://edgeguides.rubyonrails.org/getting_started.html#creating-a-new-rails-project) to install them. \
_Note: You have to use `yarn`, not `npm`. If you want to use `npm` you have to modify some configuration which is out of the scope of this recipe._
2. Create a new rails app:
```bash
rails new blog
```
Note: If you have just installed rails on your machine, you might get an error saying that rails is not installed. Simply close the terminal and open a new session and try creating a new app again.
3. Start the server to confirm all works OK:
```bash
cd blog
./bin/rails server
```
If you haven't changed any of the configuration, you should be able to open up your new app at `http://localhost:3000`.

# Install Honeybadger's webpack plugin

1. Stop the server (`ctrl+c`) and install honeybadger's webpack plugin:
```bash
yarn add @honeybadger-io/webpack --dev
```
2. Locate webpack configuration in your project and include the honeybadger's plugin. By default, it should be in `config/webpack/environment.js`. Replace the contents of this file with the following:
```javascript
const { environment } = require('@rails/webpacker')
const HoneybadgerSourceMapPlugin = require('@honeybadger-io/webpack')

// Assumes Heroku / 12-factor application style ENV variables
// named GIT_COMMIT, HONEYBADGER_API_KEY, ASSETS_URL
const revision = process.env.GIT_COMMIT || 'master'

environment.plugins.append(
  'HoneybadgerSourceMap',
  new HoneybadgerSourceMapPlugin({
    apiKey: process.env.HONEYBADGER_API_KEY,
    assetsUrl: process.env.ASSETS_URL,
    silent: false,
    ignoreErrors: false,
    revision: revision
  }))

module.exports = environment
```
3. You will have to supply `HONEYBADGER_API_KEY` and `ASSETS_URL` environment variables. You can do that with the [`figaro` gem](https://github.com/laserlemon/figaro). Open `Gemfile` and add the following inside development and test groups:
```bash
gem 'figaro'
```
The end result should look something like this:
```bash
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'figaro'
end
```
Run:
```bash
bundle install # install gem
bundle exec figaro install #setup figaro
```
Open `config/application.yml` (created from the previous command) and set the two variables:
```yaml
HONEYBADGER_API_KEY: 'YOUR_API_KEY'
ASSETS_URL: 'YOUR_ASSETS_URL'
```
The assets url is the public url of your project, usually _www.myproject.com_ or _www.myproject.com/public_. You can simply set this to a dummy value for now just to test that you can upload the source maps, i.e. _localhost_.

# Test that source maps are uploaded to Honeybadger
1. Start the server
```bash
./bin/rails server
```
2. Navigate to the app with a browser and inspect terminal output. Wait for the page to load and then you should see a message that source maps have been uploaded to Honeybadger API.
Look for `Uploaded js/application-e421b4aa3f716bebdab1.js.map to Honeybadger API` below:
```bash
% ./bin/rails server
=> Booting Puma
=> Rails 6.1.4.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.5.2 (ruby 3.0.2-p107) ("Zawgyi")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 39134
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2021-11-10 14:43:04 +0200
   (0.9ms)  SELECT sqlite_version(*)
   (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by ArticlesController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering articles/index.html.erb within layouts/application
  Article Load (0.2ms)  SELECT "articles".* FROM "articles"
  ↳ app/views/articles/index.html.erb:4
  Rendered articles/index.html.erb within layouts/application (Duration: 9.7ms | Allocations: 4735)
[Webpacker] Compiling...
[Webpacker] Compiled all packs in /Users/pangratios/Work/honeybadger/blog-rails-webpacker/public/packs
[Webpacker] 

Uploaded js/application-e421b4aa3f716bebdab1.js.map to Honeybadger API
Hash: e2a8a876c5815bee1e21
Version: webpack 4.46.0
Time: 2428ms
Built at: 11/10/2021 2:43:09 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-e421b4aa3f716bebdab1.js    125 KiB  application  [emitted] [immutable]  application
js/application-e421b4aa3f716bebdab1.js.map    139 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              
Entrypoint application = js/application-e421b4aa3f716bebdab1.js js/application-e421b4aa3f716bebdab1.js.map
[./app/javascript/channels sync recursive _channel\.js$] ./app/javascript/channels sync _channel\.js$ 160 bytes {application} [built]
[./app/javascript/channels/index.js] 211 bytes {application} [built]
[./app/javascript/packs/application.js] 492 bytes {application} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {application} [built]
    + 3 hidden modules

  Rendered layout layouts/application.html.erb (Duration: 5064.7ms | Allocations: 12176)
Completed 200 OK in 5087ms (Views: 5070.1ms | ActiveRecord: 0.7ms | Allocations: 16616)
```

**Comment by joshuap** [comment]
Thanks!! I moved the guide to notion: https://www.notion.so/honeybadger/Rails-Webpacker-Source-Map-Uploads-90f5a0c18eea4d1a8ee6473467334742
