### ISSUE TITLE
integration with `create-react-app`?

### ISSUE THREAD

**Issue by christiangenco** [honeybadger-io/honeybadger-webpack#4]
Do apps created with `create-react-app` need to be ejected to use `honeybadger-webpack`?

Without being ejected, `webpack.config.js` isn't exposed in `create-react-app` apps :(

**Comment by monde** [comment]
@christiangenco I'm not familiar with the use of `create-react-app`. This blog post seems related to your question: [Using Webpack with Create React App](https://www.fullstackreact.com/p/using-webpack-with-create-react-app/)

**Comment by Tolsee** [comment]
@monde The thing is we do not have create documentation of how to use honey-badger in frontend application. This is not of course a place to ask question but documentation can be clearer than what we have now.

**Comment by joshuap** [comment]
@Tolsee I just wanted to mention that if you need help getting started with Honeybadger, you can always email us at support@honeybadger.io!

**Comment by lucasdeassis** [comment]
@Tolsee the alternatives I've found were:

1 - Eject Create React App(CRA) to use webpack and then adding this package
2- Use `React App Rewired` to override CRA webpack config and add this package to the plugins
3 - Use the  Honeybadger Upload API](https://docs.honeybadger.io/api/source-maps.html)

Using the upload API worked best for me. I ran something like

```
curl -X POST https://api.honeybadger.io/v1/source_maps \
    -F api_key=aaaaaaa \
    -F revision=master \
    -F minified_url=https://url/static/*.js \
    -F source_map=@build/static/js/file.js.map \
    -F minified_file=@build/static/js/file.js
```

right after deploying to prod, downloading the minified and source map files from prod url.

You can add a script post deploy to automatize

**Comment by 0xhjohnson** [comment]
@Tolsee @christiangenco This issue is quite old but hopefully it helps the next person.
1. Follow [craco](https://github.com/sharegate/craco/blob/master/packages/craco/README.md#installation) installation instructions
2. Create `craco.config.js` file and add [honeybadger-io/webpack](https://github.com/honeybadger-io/honeybadger-webpack#readme) plugin which will automatically upload sourcemaps for production.
```js
const { whenProd } = require('@craco/craco');
const HoneybadgerSourceMapPlugin = require('@honeybadger-io/webpack');

const revision = process.env.REACT_APP_VERCEL_GIT_COMMIT_SHA || 'master';

module.exports = {
  webpack: {
    plugins: [
      ...whenProd(
        () => [
          new HoneybadgerSourceMapPlugin({
            apiKey: process.env.REACT_APP_HONEYBADGER_KEY,
            assetsUrl: `https://${process.env.REACT_APP_VERCEL_URL}`,
            revision: revision
          })
        ],
        []
      )
    ]
  }
};

```
