### ISSUE TITLE
Unable to upload large source map files (38MB)

### ISSUE THREAD

**Issue by sljavi** [honeybadger-io/honeybadger-webpack#7]
Hey guys,

I want to ask you about source map file size limitations.

After the bundle and source maps files are generated I see the following console error

```
ERROR in HoneybadgerSourceMapPlugin: failed to upload app.bundle.js.map to Honeybadger API: Unexpected token < in JSON at position 0
```

The filename `app.bundle.js.map` is correct and its content is a well made JSON also.

Since the error `Unexpected token < in JSON at position 0` doesn't make sense I inspected the Honeybadger's sever call and I found the following response

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

So I guess the server is unable the handle a source map file of 38MB

**Could you increase that limit?**

Just in case this is my webpack plugin config

```
{
  ...,
  plugins: [
    ...,
    new HoneybadgerSourceMapPlugin({
      apiKey: 'a_real_api_key',
      assetsUrl: 'https://theAppDomain.com/',
      revision: 'the_git_commit_hash'
    })
  ]
}
```

**Comment by stympy** [comment]
I have bumped up the limit -- let me know if that works for you.

**Comment by sljavi** [comment]
that was faster than immediately 😮 
now I can not reproduce the issue
thanks @stympy
