### ISSUE TITLE
Upload success log message not showing

### ISSUE THREAD

**Issue by lucasdeassis** [honeybadger-io/honeybadger-webpack#80]
## What are the steps to reproduce this issue?

1. Add Honeybadger plugin to webpack
```
  plugins: [
    new HoneybadgerSourceMapPlugin({
      apiKey: process.env.HONEYBADGER_API_KEY,
      assetsUrl: '*/assets',
      revision: process.env.GIT_REVISION,
    }),
  ],
```
2. … compile webpack production build with trace like`$ NODE_ENV=production rake webpack:compile --trace` or `webpack compile --verbose` and see it completing successfully

## What happens?
The success upload message is not being displayed

## What were you expecting to happen?
A message like Uploaded ${sourceMap} to Honeybadger API. As in line [76](https://github.com/honeybadger-io/honeybadger-webpack/blob/957b976f42b37fa32de745709d2b7b340b15cc00/src/HoneybadgerSourceMapPlugin.js#L76) on `HoneybadgerSourceMapPlugin.js`

## Any logs, error output, etc?
No

## What versions are you using?
**Operating System:** macOS high sierra 10.13
**Package Version:** 1.1.2

**Comment by joshuap** [comment]
@lucasdeassis I'm not quite sure how to handle this one, since we're just calling `console.log`. It seems like it would be best to rely on whatever the default node behavior is for `console` logging, wouldn't it? I'm willing to consider suggestions.
