### ISSUE TITLE
assetsUrl in HoneybadgerSourceMapPlugin not working if contains final slash "/"

### ISSUE THREAD

**Issue by lucasdeassis** [honeybadger-io/honeybadger-webpack#81]
## What are the steps to reproduce this issue?

1. Add Honeybadger plugin to webpack with `assetsUrl` including a final slash (`/`) 
```
  plugins: [
    new HoneybadgerSourceMapPlugin({
      apiKey: process.env.HONEYBADGER_API_KEY,
      assetsUrl: '*/assets/',
      revision: process.env.GIT_REVISION,
    }),
  ],
```
2. compile bundle with webpack performing the sourcemap upload

## What happens?
sourcemaps are uploaded wrongly and not applied in honeybadger errors

## What were you expecting to happen?
To work normally as `assetsUrl: '*/assets',`, that is, without the final slash ? or not ? if not, it'd help if some info regarding assets path. I mean, in other webpack configs, when it is a path (a folder somehow), ends with a `/` (slash).

## What versions are you using?
**Package Version:** 1.1.2

**Comment by joshuap** [comment]
@lucasdeassis this should be fixed in 1.1.4. Let me know if not. Thanks for reporting!
